### ISSUE TITLE
moment dependency

### ISSUE THREAD

**Issue by DSpeichert** [mad-eye/pince#10]
Not sure if it's a problem in this package or another package depending on it.

```
W20150723-01:45:49.101(2)? (STDERR)           
W20150723-01:45:49.101(2)? (STDERR) /home/dd/.meteor/packages/meteor-tool/.1.1.3.19hb9g++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150723-01:45:49.102(2)? (STDERR)                                             throw(ex);
W20150723-01:45:49.102(2)? (STDERR)                                                   ^
W20150723-01:45:49.115(2)? (STDERR) Error: Can't find npm module 'moment'. Did you forget to call 'Npm.depends' in package.js within the 'jag_pince' package?
W20150723-01:45:49.115(2)? (STDERR)     at Object.Npm.require (/srv/spigu/.meteor/local/build/programs/server/boot.js:155:17)
W20150723-01:45:49.115(2)? (STDERR)     at __coffeescriptShare (packages/jag:pince/src/consoleOutput.coffee:6:16)
W20150723-01:45:49.115(2)? (STDERR)     at packages/jag:pince/src/consoleOutput.coffee:1:1
W20150723-01:45:49.115(2)? (STDERR)     at packages/jag:pince/src/logger.coffee:1:1
W20150723-01:45:49.115(2)? (STDERR)     at /srv/spigu/.meteor/local/build/programs/server/boot.js:222:10
W20150723-01:45:49.116(2)? (STDERR)     at Array.forEach (native)
W20150723-01:45:49.116(2)? (STDERR)     at Function._.each._.forEach (/home/dd/.meteor/packages/meteor-tool/.1.1.3.19hb9g++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150723-01:45:49.116(2)? (STDERR)     at /srv/spigu/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by tcastelli** [comment]
+1

**Comment by jagill** [comment]
Please try it again with the latest version (0.0.8), and tell me if there are any problems!

**Comment by DSpeichert** [comment]
That works, thanks a lot!
