### ISSUE TITLE
MyLog.error fails with TypeError: _this.handleLog is not a function

### ISSUE THREAD

**Issue by welelay** [mad-eye/pince#12]
There seems to be a special case for error level log, but I have trouble to understand the code.
Please can you tell me where should the handleLog function be declared ?

**Comment by jagill** [comment]
Thanks for finding this!  Fix this in master, published to meteor.  Will publish to npm later tonight.

**Comment by welelay** [comment]
Great !
Thanks for the quick fix. It works now.

**Comment by jsamr** [comment]
**regression** on v 0.0.9, npm 
Incriminated lines : 

``` coffeescript
Logger     = require "pince"
prefix     = "media-node:init"
logger     = new Logger prefix
logger.error "TEST"
```

``` shell
TypeError: Object #<Listener> has no method 'handleLog'
  at Logger.<anonymous> (/home/svein/Programming/WebstormProjects/video-node/node_modules/pince/dist/pince-node.js:194:26)
  at Logger.EventEmitter.emit (events.js:95:17)
  at Logger._log (/home/svein/Programming/WebstormProjects/video-node/node_modules/pince/dist/pince-node.js:284:24)
  at Logger.error (/home/svein/Programming/WebstormProjects/video-node/node_modules/pince/dist/pince-node.js:320:19)
  at Object.<anonymous> (/home/svein/Programming/WebstormProjects/video-node/src/init.coffee:10:8)
  at Object.<anonymous> (/home/svein/Programming/WebstormProjects/video-node/src/init.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/svein/Programming/WebstormProjects/video-node/src/app.coffee:1:1)
  at Object.<anonymous> (/home/svein/Programming/WebstormProjects/video-node/src/app.coffee:1:1)
  at Module._compile (module.js:456:26)
```

**Comment by jagill** [comment]
@sveinburne I can't reproduce this.  Does it still happen if you do a clean install?
